# Generated by Django 3.2.16 on 2022-11-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_identifier',
            name='c_nomenclature',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='patient_identifier',
            name='variant_protein',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.DeleteModel(
            name='variant_information',
        ),
    ]
