# Generated by Django 4.1.3 on 2022-11-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_identifier',
            name='Stage',
            field=models.CharField(default='blank', max_length=100),
        ),
    ]
